version: 2.1
jobs:
  build:
    parameters:
      python-version:
        type: string
    environment:
      XDMOD_10_5_IMAGE: tools-ext-01.ccr.xdmod.org/xdmod-10.5.0-x86_64:rockylinux8.5-0.3
      XDMOD_11_0_IMAGE: tools-ext-01.ccr.xdmod.org/xdmod:x86_64-rockylinux8.9.20231119-v11.0.0-1.0-03
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            python -m pip install flake8 flake8-commas flake8-quotes pytest
            python -m pip install -e .
      - run:
          name: Lint with Flake8
          command: python3 -m flake8 . --max-complexity=10 --show-source --exclude __init__.py
      - setup_remote_docker
      - run:
          name: Spin up containers for testing against different XDMoD web server versions
          command: docker compose -f .circleci/docker-compose.yml up -d
      - run:
          name: Create a file with 10,000 users
          command: |
            # This allows us to test filters that have more than 10,000 values
            for i in {1..10000}; do
              # Pick a timestamp such that the jobs span multiple quarters
              unix_timestamp=$((1498866840 + $i * 2))
              echo "$i|2269212|frearson|black|banana-cream|caste|caste|45580|user$i|379330|$(date --utc +'%Y-%m-%dT%H:%M:%S' -d @$unix_timestamp)|$(date --utc +'%Y-%m-%dT%H:%M:%S' -d @$(($unix_timestamp + 1)))|$(date --utc +'%Y-%m-%dT%H:%M:%S' -d @$(($unix_timestamp + 2)))|$(date --utc +'%Y-%m-%dT%H:%M:%S' -d @$(($unix_timestamp + 3)))|2-23:24:40|0:0|COMPLETED|1|16|16|62.50Gn|cpu=16,mem=62.50G,node=1|billing=16,cpu=16,mem=62.50G,node=1|3-00:00:00|cpn-m25-02-01|310f6011b278ebb15df2d199e0119de78d261d8c478a203abc97dc3dda7702ae" >> 10000users.log
            done
      - run:
          name: Install yq
          command: |
            sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
            sudo chmod +x /usr/bin/yq
      - run:
          name: Test against each XDMoD web server version
          command: |
            declare -a portal_versions=$(yq '.services | keys[]' .circleci/docker-compose.yml)
            for version in $portal_versions; do
              # Copy certificate from container
              docker cp $version:/etc/pki/tls/certs/localhost.crt $version.crt
              export CURL_CA_BUNDLE="$version.crt"
              # Determine XDMoD host
              ports=$(yq ".services.\"$version\".ports[0]" .circleci/docker-compose.yml)
              port=$(echo $ports | cut -d ':' -f 1)
              export XDMOD_HOST="https://localhost:$port"
              # Get XDMoD API token
              token=$(curl \
                -X POST \
                -c xdmod.cookie \
                -d 'username=normaluser&password=normaluser' \
                $XDMOD_HOST/rest/auth/login \
                | jq -r '.results.token' \
              )
              echo -n 'XDMOD_API_TOKEN=' > ~/.xdmod-data-token
              curl \
                -X POST \
                -b xdmod.cookie \
                $XDMOD_HOST/rest/users/current/api/token?token=$token \
                | jq -r '.data.token' \
                >> ~/.xdmod-data-token
              # Copy the 10,000 users file into the container and shred it
              docker cp 10000users.log $version:10000users.log
              docker exec $version xdmod-shredder -r frearson -f slurm -i 10000users.log
              # Ingest and aggregate
              date=$(date --utc +%Y-%m-%d)
              docker exec $version xdmod-ingestor --ingest
              docker exec $version xdmod-ingestor --aggregate=job --last-modified-start-date $date
              # Run tests
              export XDMOD_VERSION="$version"
              coverage run --branch --append -m pytest -vvs -o log_cli=true tests/
            done
      - run:
          name: Make sure 100% code coverage
          command: coverage report -m --fail-under=100
workflows:
  full-build:
    jobs:
      - build:
          matrix:
            parameters:
              python-version:
                - "3.13"
                - "3.12"
                - "3.11"
                - "3.10"
                - "3.9"
                - "3.8"
