version: 2.1
jobs:
  build:
    parameters:
      python-version:
        type: string
    environment:
      XDMOD_10_5_IMAGE: tools-ext-01.ccr.xdmod.org/xdmod-10.5.0-x86_64:rockylinux8.5-0.3
      XDMOD_11_0_IMAGE: tools-ext-01.ccr.xdmod.org/xdmod:x86_64-rockylinux8.9.20231119-v11.0.0-1.0-03
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            python -m pip install flake8 flake8-commas flake8-quotes pytest coverage
            python -m pip install -e .
      - run:
          name: Lint with Flake8
          command: python3 -m flake8 . --max-complexity=10 --show-source --exclude __init__.py
      - setup_remote_docker
      - run:
          name: Spin up containers for testing against different XDMoD web server versions
          command: docker compose -f .circleci/docker-compose.yml up -d
      - run:
          name: Install yq
          command: |
            sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
            sudo chmod +x /usr/bin/yq
      - run:
          name: Test against each XDMoD web server version
          command: |
            declare -a portal_versions=$(yq '.services | keys' .circleci/docker-compose.yml)
            echo $portal_versions
      - run:
          name: Make sure 100% code coverage
          command: python3 -m coverage report -m --fail-under=100
workflows:
  full-build:
    jobs:
      - build:
          matrix:
            parameters:
              # Test the minimum supported and latest Python versions:
              python-version:
                - "3.8"
                - "3.13"
