version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Spin up containers and test different Python versions against different XDMoD web server versions
          command: ./tests/ci/scripts/run-tests.sh
