version: 2.1
jobs:
  build:
    environment:
      MIN_PYTHON_VERSION: "3.8"
      MAX_PYTHON_VERSION: "3.13"
      XDMOD_10_5_IMAGE: tools-ext-01.ccr.xdmod.org/xdmod-10.5.0-x86_64:rockylinux8.5-0.3
      XDMOD_11_0_IMAGE: tools-ext-01.ccr.xdmod.org/xdmod:x86_64-rockylinux8.9.20231119-v11.0.0-1.0-03
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Spin up containers and test different Python versions against different XDMoD web server versions
          command: ./tests/ci/scripts/run-tests.sh
