services:
  xdmod-main-dev:
    container_name: xdmod-main-dev
    image: ${XDMOD_11_0_IMAGE}
    tty: true
    ports:
      - 8081:443
  xdmod11.0:
    container_name: xdmod11.0
    image: ${XDMOD_11_0_IMAGE}
    tty: true
    ports:
      - 8082:443
  xdmod10.5:
    container_name: xdmod10.5
    image: ${XDMOD_10_5_IMAGE}
    tty: true
    ports:
      - 8083:443
